### PR TITLE
Update fusion360.yml

### PR DESCRIPTION
**Pull request by DakJack**
Adjusted URL for installer.

### CODE REVIEW

**Comment by alextrical** [comment]
This is a duplicate of #296

**Comment by OzzieOrca** [comment]
@alextrical yes, but https://github.com/bottlesdevs/programs/pull/296 didn't get merged. It was automatically closed by https://github.com/bottlesdevs/dependencies/pull/220 which added the newly required "WebView2 Runtime" but that didn't include the url change.

**Comment by alextrical** [comment]
@OzzieOrca Agreed, the WebView2 was intended to be suplimental, not instead of.

There are a few more tweaks needed to get the software to let the user Login post the January Update/Rebrand.

I have a working Yaml, bar one additional script to create a .desktop file to handle the Mimetype. Unfortunately as of yet there has been no communication from the community as to if it's possible to:
Create a cuatom .desktop file on the host
Register a Mimetype on the host
Check the minimum version of Wine being installed on. Wine 8.14 is now the minimum supported for this application

**Comment by mirkobrombin** [comment]
Do you want to keep working on this before merging?

**Comment by alextrical** [comment]
@mirkobrombin Could you please merge in the current change, and I will get a fully tested PR made tomorrow, along with the scripts required to be run by the end users to get the Mimetype redirection working to allow login.

**Comment by alextrical** [comment]
@mirkobrombin yes if that is possible please close this and merge #299 as it contains this PR's alongside additional fixes to make the ability to login functional, since the legacy methods assumed here no longer work, post the January update

**Pull request closed without merging**
