### PR TITLE
Update Fl studio to the latest version

### PR DESCRIPTION
**Pull request by meesvw**
Update FL studio to latest version & added correct MD5 checksum.

Fixes #(issue)

## Type of change
- [ ] New installer
- [ ] Manifest fix
- [x] Other

# Whas This Tested Using a [Local Repository](https://maintainers.usebottles.com/Testing)?
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by meesvw** [comment]
Quick note the sounds tab for the FL studio cloud does not work. I cannot get the right output in the console to see what is missing, however I do get the following:

First error:
```
03dc:err:ole:marshal_object Failed to create an IRpcStubBuffer from IPSFactory for {e89f726e-c4f4-4c19-bb19-b647d7fa8478} with error 0x80004002
```
Second error:
```
0c00:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Internal.Security.WebAuthentication.AuthenticationManager"
```

Third error:
```
06c0:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
```

**Comment by mirkobrombin** [comment]
Can you update the review? https://github.com/bottlesdevs/programs/blob/main/Reviews/flstudio.md

For the issues, looks like a new dependency got introduced. I saw something very similar a long time ago, just installing a dependency fixed it (but I do not remember which one D:)

**Comment by meesvw** [comment]
Yes I'll update the review! However I am looking to see if I can fix the issue with the FL cloud tab. If I can't find anything tonight I'll just commit the update to the review.

**Comment by mirkobrombin** [comment]
I could take a look at some point

**Comment by meesvw** [comment]
@mirkobrombin updated the review accordingly, unfortunately could not find a fix for the errors generated when opening the FL cloud sounds library. Please check if the review does not contain incorrect information.

**Comment by mirkobrombin** [comment]
Looks good to me. I can merge if you have no more fixes to add

**Comment by meesvw** [comment]
> Looks good to me. I can merge if you have no more fixes to add

Nope tested some more things, but so far no luck. My knowledge is too limited on this part unfortunately. But won't quit!

**Pull request merged**
