### PR TITLE
add Ableton Live installer

### PR DESCRIPTION
**Pull request by nickberry17**

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Thanks for your contribution. I'll test asap

**Review by mirkobrombin — COMMENTED** [review]
the icon background should be transparent, the rest looks okay, I'll try the installation shortly

**Comment by nickberry17** [comment]
If you don't have a license you can download a free trial here. I didn't want to limit the installer to just the trial, or a specific version, which is why I have the user supply the installer exe. 

https://www.ableton.com/en/trial/

**Comment by mirkobrombin** [comment]
> If you don't have a license you can download a free trial here. I didn't want to limit the installer to just the trial, or a specific version, which is why I have the user supply the installer exe.
> 
> https://www.ableton.com/en/trial/

makes sense

**Comment by nickberry17** [comment]
Pushed with new png icon

**Review by mirkobrombin — APPROVED** [review]

**Comment by mirkobrombin** [comment]
Sorry for the delay, we were busy with the grk4 porting 😵‍💫

**Pull request merged**
