### PR TITLE
Fusion (Formaly Fusion 360) Post January update SSO login fix

### LINKED ISSUE #295: Fusion360 executable download URL changed
Hello,

The URL defined in fusion360.yml is no correct anymore and the installer does not work:

15:24:01 (INFO) Bottles found:
	 - Fusion360
 
15:24:01 (INFO) Catalog installers loaded 
15:24:01 (INFO) Catalog dependencies loaded 
15:24:01 (INFO) Catalog components loaded 
15:24:02 (INFO) Setting Key sync=esync for bottle Fusion360… 
15:24:02 (INFO) There is no running wineserver. 
15:38:41 (INFO) Installing dependencies 
15:38:41 (INFO) Updating bottle parameters 
15:38:41 (INFO) Setting Key dxvk=True for bottle Fusion360… 
15:38:41 (INFO) Setting Key discrete_gpu=True for bottle Fusion360… 
15:38:41 (INFO) Executing installer steps 
15:38:43 (WARNING) Failed to download [http://www.autodesk.com:80/products/fusion-360/appstream] with code: 403 != 200 
15:38:43 (ERROR) Failed to download Fusion 360 Admin Install.exe, or checksum failed. 

It seems that the correct one is now:

https://dl.appstreaming.autodesk.com/production/installers/Fusion%20Admin%20Install.exe

### PR DESCRIPTION
**Pull request by alextrical**
Fixes #295 #298 #297 #296 #278 #237 #120

Autodesk rebranded "Fusion 360" to "Fusion", this resulted in the URL change as noticed by others here. However while doing this they also removed the Legacy login method `FUSION_IDSDK=false` we have been using. This issue was raised with Wine Bug tracker, and has been patched as of Wine 8.14. 

We can now log in through the Web interface / SSO but this comes with its own challenges, specifically setting up Mime-type handling to pass the authentication back into the bottle.
I propose this PR to be classed as a Draft until we get a cleaner method to fix the following:
Remove the need for the end user to manually run a script on their system to setup the .desktop and mimetype redirection
Check the version of Wine being run on, and require Wine8.14 or higher

Currently this additional code needs to be run by the end user, on their host
```
#Setup Bottle with Known name, and Wine Version >= 8.14. No checks for bottle minimum Wine Version (is this an oversight?)
BOTTLE="Fusion"
flatpak run --command=bottles-cli com.usebottles.bottles new --bottle-name $BOTTLE --environment "custom" --arch "win64" --runner caffe-8.21
```

Open bottles and install Fusion, This can not currently be done from the CLI (is this an oversight?), you have to do this yourself

It seems we cant define a second application in the YAML manifest, use the script below instead (is this an oversight?)
```
BOTTLE="Fusion"

#Define a new application link, that we will use for handling the Mimetype. Can we add this hidden?
flatpak run --command=bottles-cli com.usebottles.bottles add --bottle $BOTTLE -n "AdskIdentityManager" -p "$HOME/.var/app/com.usebottles.bottles/data/bottles/bottles/$BOTTLE/drive_c/Program Files/Autodesk/webdeploy/production/99249ee497b13684a43f5bacd5f1f09974049c6b/Autodesk Identity Manager/AdskIdentityManager.exe" 

#Create mimetype link to handle web login call backs to the Identity Manager
cat > $HOME/.local/share/applications/adskidmgr-opener.desktop << EOL
[Desktop Entry]
Type=Application
Name=adskidmgr Scheme Handler
Exec=flatpak run --command=bottles-cli com.usebottles.bottles run --args-replace -b $BOTTLE -p "AdskIdentityManager" "%u"
StartupNotify=false
MimeType=x-scheme-handler/adskidmgr;
EOL
xdg-mime default adskidmgr-opener.desktop x-scheme-handler/adskidmgr
```

This PR contains:
Updated Icon
Renamed manifest to align with product rebrand
added screenshot of application installed on linux
changed installer web link location to account for rebrand

## Type of change
- [ ] New installer
- [x] Manifest fix
- [ ] Other

# Whas This Tested Using a [Local Repository](https://maintainers.usebottles.com/Testing)?
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by OzzieOrca** [comment]
@alextrical once this gets merged, are there still some scripts that need to be run to make Fusion usable? Is that the MIME type handler? Could you document what a user still needs to run manually until a better solution is figured out? That'd be helpful, at least to me :) Thanks!

**Comment by mirkobrombin** [comment]
> No luck getting anything working through run_script
> No file creation, no echo printed to terminal or GUI that i can see, and no tracking of any errors raised (I would expect the system to not report success when I raise an error)

That's weird. So basically it does nothing? I didn't used it in a while but I remember I tested it and was working.

**Comment by alextrical** [comment]
> @alextrical once this gets merged, are there still some scripts that need to be run to make Fusion usable? Is that the MIME type handler? Could you document what a user still needs to run manually until a better solution is figured out? That'd be helpful, at least to me :) Thanks!

@OzzieOrca Yes the scripts I've listed above are unfortunately currently still required to create the Mime Type handler.
I am happy to document the script required to be run by the end users. Is there a place that those notes should be made to be visible?

**Comment by alextrical** [comment]
@mirkobrombin yes, from the test I did, I couldn't seem to run any commands with any visible output. Be it creating a file or echo'ing. I will try some more tests this evening to see if I can get it to do anything

**Pull request merged**
