### PR TITLE
Add 20-sim

### PR DESCRIPTION
**Pull request by katepavlu**
Adds [20-sim](https://www.20sim.com/). Program installs, license activation works, program itself works. 

Know issue: Simulation graphs can become glitchy if the file is saved while the graph is fullscreened. This issue is fixed in Wine 9.21.

## Type of change
- [x] New installer
- [ ] Manifest fix
- [ ] Other

# Whas This Tested Using a [Local Repository](https://maintainers.usebottles.com/Testing)?
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by katepavlu** [comment]
The dependencies were obtained from the developer in a support email. Contact me if you want a demonstration of either program working (I have a licenses valid until February 25).

**Comment by katepavlu** [comment]
added review

**Comment by katepavlu** [comment]
should be ready now

**Comment by jntesteves** [comment]
LGTM

**Pull request merged**
