### PR TITLE
Star Citizen and Enlisted Launcher

### PR DESCRIPTION
**Pull request by EvoXCX**

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Thanks for your contribution

**Comment by EvoXCX** [comment]
Arguments are wrong, replace libglesv2=b to libglesv2=builtin

**Comment by mirkobrombin** [comment]
> Arguments are wrong, replace libglesv2=b to libglesv2=builtin

'b` is the same as `builtin`. Did you have tried and it doesn't work with `b`?

**Comment by EvoXCX** [comment]
Do not work with b but it's work with builtin

**Comment by mirkobrombin** [comment]
> Do not work with b but it's work with builtin

Thanks for response

**Comment by mirkobrombin** [comment]
Hi @EvoXCX thanks for your contributions! You came at the right time, because the installers feature will be released as stable with the next release.

Just a note: remember that the review is post-installation, where by installation we mean the entire process performed by Bottles, including tricks like registering a DLL Override.

**Comment by mirkobrombin** [comment]
I'll merge this soon, the `userdir/` placeholder is almost ready and can be used to launch executables from the user directory

**Review by mirkobrombin — COMMENTED** [review]
Waiting for 2022.2.28  to merge due to `userdir/` placeholder.

**Pull request merged**
