### PR TITLE
Add FL Studio

### PR DESCRIPTION
**Pull request by BobyMCbobs**
Adds FL Studio to the supported list of installers

### CODE REVIEW

**Comment by BobyMCbobs** [comment]
Currently FL Studio just freezes after installation. I haven't reinstalled FL Studio in a while, so it's possible that there's something with the latest FL or the way it's installed. Not sure yet!

**Comment by mirkobrombin** [comment]
Thanks for submitting! I will test in the day, can you also publish the review in the dedicated path?

**Comment by BobyMCbobs** [comment]
> Thanks for submitting! I will test in the day, 

Cheers @mirkobrombin. 

> can you also publish the review in the dedicated path?

How do you mean?

**Comment by mirkobrombin** [comment]
A file like this https://github.com/bottlesdevs/programs/blob/main/Reviews/epicgamestore.md

so it should be placed in Reviews/flstudio.md

https://github.com/bottlesdevs/programs/blob/main/GUIDELINES.md#valuation-tests

**Comment by mirkobrombin** [comment]
I have tested the installer and it works fine. I'm fine with merge when the review is ready.

**Pull request merged**
