### PR TITLE
Updates to Star Citizen

### PR DESCRIPTION
**Pull request by ProjectSynchro**
Supports the new 2.0 launcher, as well as updates the 'review' which reflects the experience playing the game.

Adding the allfonts dependency also fixes launches in the standard runners.

## Type of change
- [ ] New installer
- [x] Manifest fix
- [ ] Other

# Was This Tested Using a [Local Repository](https://maintainers.usebottles.com/Testing)?
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by ProjectSynchro** [comment]
This is ready to go, let me know if there is anything I should do in terms of changing the review of the application. 

With these tweaks this should bring Star Citizen to a Platinum rating as it works OOTB with no tweaks.

**Comment by mirkobrombin** [comment]
Does it work with the default runner Soda?

**Comment by ProjectSynchro** [comment]
> Does it work with the default runner Soda?
It does.
The base pack downloads correctly (was previously an issue with prior 2.0.x launcher releases)

I ran a full install from scratch (takes a while, but this is more or less expected), as well as tested the verification behaviour. All work as expected.

I also reduced the amount of fonts needed to be installed which saves on the program's initial install time.

**Comment by mirkobrombin** [comment]
Working otb with Soda means it's platinum. Well done, I can merge if the PR is ready.

**Comment by ProjectSynchro** [comment]
It's good to go, feel free to merge :smile:

**Pull request merged**
