### PR TITLE
Add Medal.tv Installer

### PR DESCRIPTION
**Pull request by azpha**
Fixes #(issue)

## Type of change
- [x] New installer
- [ ] Manifest fix
- [ ] Other

# Whas This Tested Using a [Local Repository](https://maintainers.usebottles.com/Testing)?
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Thanks for your contribution. I think the download link is broken

**Comment by jannuary** [comment]
I wonder how warranted this is as an installer, considering the selling feature is broken and it only requires one fairly common dependency

**Comment by azpha** [comment]
Uh oh, looks like that subdomain doesn't want to resolve consistently. I'll update with the direct setup URL if y'all think this should be an installer

**Comment by mirkobrombin** [comment]
it automate the process of installing that single dependency and therefore it is useful for someone

**Pull request merged**
